const aiglaText := "Os Aiglanos são um povo astuto e inclusivo, conhecido por sua capital Aquileia. Sua bandeira apresenta uma águia dourada em um fundo vermelho, simbolizando a seleção dos capazes. Eles são um povo mestiço, com variação de tom de pele, altura e tipo de cabelo. São disciplinados, valorizam a história e fazem do exercício físico um hábito.
Historicamente, os Aiglanos prosperaram apesar dos desafios, aprendendo com suas fraquezas e remodelando-se. Passaram de um pequeno vilarejo para uma República, com um sistema político fechado. A ascensão do Imperador Crassus trouxe um período de bonança, com reformas militares e de governo que expandiram o poder do império.
A religião Aiglana é flexível, absorvendo divindades dos povos conquistados através do ritual de evocatio. Os costumes incluem uma nobreza intocável, lealdade à legião e pagamento dos legionários durante campanhas.
Em resumo, os Aiglanos são um povo resiliente e adaptável, com uma história marcada por conquistas militares e uma cultura diversificada.";

const lesteText := "Os Povos do Leste são caracterizados por sua extensa terra, liderada pela Dinastia Huang, com uma cultura diversificada apesar da unificação sob uma única dinastia. O gentílico varia de acordo com a classe social, com destaque para os kamis, heimins e heinins. A pele clara a amarelada e olhos com palpebras puxadas são características comuns.
A história remonta à unificação sob a Dinastia Huang, que governa há milênios, marcada por conflitos e unificações. A religião central é o culto ao Deus-dragão, que permeia todas as camadas da sociedade, especialmente através dos monges e samurais, que seguem uma rígida disciplina e código de honra.
A ascensão do atual Imperador, Fan Huang, marcou uma mudança drástica na dinastia, com a extinção do culto ao dragão e a ampliação da Grande Muralha, levando ao surgimento da 'Fúria do Dragão' e uma onda de refugiados.
A religião Kai é central na vida dos povos do Leste, baseada na lealdade absoluta ao Imperador como mensageiro do Deus-dragão. A história mitológica envolve a transformação do primeiro imperador em um dragão dourado.
Curiosidades incluem a simplicidade dos monges, a saga dos ronins, a importância do peixe na dieta e a cremação como ritual funerário. Rumores sobre uma ordem assassina chamada sicários ainda pairam sobre a região.
A fisionomia varia, mas os povos do Leste são geralmente de estatura média, com pele clara a amarelada e cabelos escuros. Suas vantagens raciais incluem habilidades de combate e a habilidade de se tornarem monges e samurais. A língua comum é Haiei.";

const harolothText := "Os Drows são uma raça de elfos negros com pele escura e olhos variados, mas com íris claras, muitas vezes brilhantes na escuridão. São de estatura média, com as fêmeas geralmente mais baixas do que os machos. Seu estilo de combate privilegia emboscadas e ataques sorrateiros, evitando confrontos diretos.
A origem dos Drows é envolta em mistério, mas acredita-se que tenham surgido nos subterrâneos do continente. Sua sociedade é marcada pelo conflito interno e pela busca pelo raro minério Illyra, fonte de poder e riqueza para suas casas.
A religião dos Drows gira em torno de Idrith, uma deusa sacrificada pelo bem-estar de todos. Sua sociedade é baseada no medo, com o Clero de Idrith, a Liga de Comerciantes e o Braço Armado sendo as principais instituições. A nobreza drow é dividida em castas, onde o poder e a influência são os principais critérios de avaliação.
Curiosidades sobre os Drows incluem sua falta de afeto infantil, a importância das fêmeas na sociedade, sua apreciação por arte e música, orgulho racial e conhecimento da língua comum. Embora possam agir de forma imprevisível individualmente, os Drows são impiedosos e implacáveis em sua busca por poder quando em sociedade.";

const bjorskaText := "Os Björske são um povo tradicional do norte do continente de Eora, conhecidos por sua pele alva e cabelos que variam do preto ao loiro e ruivo. São orgulhosos, valentes e generosos, transmitindo suas tradições oralmente, reunindo-se em torno de fogueiras para cultuar seus deuses com danças, carne de caça e hidromel.
Sua história remonta a tribos antigas que enfrentaram grande fome e ataques dos Aiglanos, sendo lideradas por Brago, um líder astuto e forte. Ele uniu as tribos, lutou contra os invasores e estabeleceu o reinado dos Björske, sendo adorado mesmo após sua morte.
A religião dos Björske, chamada Haulleuad, é centrada no culto ao Sol e à Lua, representando força, proteção e fertilidade. O pai, Duw, o Deus Sol, e a mãe, Lleuad, a Lua, são adorados em festivais e rituais que celebram a natureza e os ciclos da vida.
Os Björske são guerreiros habilidosos, especialmente montados, utilizando cavalaria e formação de escudos em combate. São conhecidos por sua fúria e tradição, valorizando a força e a fertilidade. Sua cultura valoriza a oralidade e a música, enquanto sua língua nativa é o Björ e também falam o Comum.";

const alurielText := "TO BE ANNOUNCED";

const polkineaText := "Os Polski são um povo diverso e tranquilo, com uma estatura média de 90 centímetros e um corpo rechonchudo que varia de 20 a 30 quilogramas. Sua pele bronzeada pode variar de tons mais escuros a mais claros, e traços distintos podem indicar a linhagem familiar. Eles valorizam o conforto e a simplicidade em suas vestimentas e casas, mas têm orgulho de se vestirem bem.
Os Polski cultivam as terras de Colhesol há centenas de anos, preferindo manter-se à parte dos problemas dos povos maiores. São conhecidos por seu amor pela comida, fumo e bebidas, bem como pela paz e tranquilidade da vida no campo. Suas habilidades em cultivo e culinária são notáveis, e eles desenvolveram um comércio de especiarias e condimentos.
Divididos em três grupos principais - Pérvalhos, Cascalvas e Encostarvores - os Polski têm laços familiares fortes e um sistema político baseado em decisões comunitárias. São conhecidos por sua capacidade de passar despercebidos e por conquistar a amizade dos outros.
Os Polski não se preocupam muito com posses materiais e valorizam a hospitalidade e a simplicidade. Seus costumes incluem compartilhar ferramentas e lidar com limites e privacidade de maneira única. São habilidosos em fala e canto, apreciando a arte do improviso.
Em resumo, os Polski são criaturas simples que valorizam o conforto, a boa comida e a calmaria da vida no campo, além de serem ótimos agricultores e, em alguns casos, aventureiros.";

const baduranText := "Os Anões são uma raça distintiva, reconhecível por suas longas barbas adornadas e estatura baixa, mas robusta. Com uma cultura profundamente enraizada na forja e na tecnologia, eles habitam regiões montanhosas e possuem uma sociedade organizada, com líderes como o 'Pai' e a 'Mãe'. Sua relação com outras raças é marcada por um misto de hospitalidade e irritabilidade, especialmente com os elfos, com os quais têm uma rivalidade histórica.
Vestidos com suas melhores armaduras e tecidos, os Anões buscam demonstrar sua destreza e riqueza por meio de suas vestimentas. São inventivos em suas forjas e valorizam o trabalho árduo, considerando a terra como uma arte insuperável. A forja desempenha um papel crucial em sua identidade, transmitindo tradições e ensinamentos aos mais jovens.
Na esfera religiosa, os Anões adoram um poderoso deus criador e reverenciam seus antepassados, como Galgrumir, Killi e Thorgrim, conhecidos por suas grandes realizações. Além disso, possuem um conjunto de vantagens raciais, como resistência a magias e bônus em HP e stamina, refletindo sua constituição robusta e vontade inabalável.
Sua fortaleza, Khron Kaz'ad, é uma grandiosa construção subterrânea repleta de tesouros e minas profundas, refletindo sua habilidade em trabalhar com o ambiente montanhoso. Os Anões são tradicionalistas, leais e valorizam o trabalho árduo, características que permeiam sua cultura e comportamento.";

const gulthrakText := "Os Orcs são uma raça de humanoides guerreiros, mais altos e fortes que os humanos, com pele calejada variando do vermelho ao verde. Sua história remonta ao Deserto da Perdição, onde enfrentaram desafios extremos para sobreviver, incluindo batalhas contra criaturas perigosas chamadas Aklats. Seu modo de vida nômade foi marcado por um culto à força e à sobrevivência.
A religião dos Orcs gira em torno de Adar Kor Doom, representando os elementos areia, água e sangue, que sustentam o ciclo de vida e fertilidade. Os Xamãs são responsáveis por preservar esses ensinamentos e tradições.
Curiosidades sobre os Orcs incluem seu uso de armaduras feitas de couro, ossos e materiais encontrados, sua reverência pelas chuvas sagradas do deserto e a igualdade de gênero em sua sociedade, onde tanto machos quanto fêmeas guerreiam e lideram tribos.
Na adolescência, os Orcs são submetidos a ritos de passagem no deserto e enfrentam os perigos das dunas. A presença de forasteiros no deserto era comum, mas os Orcs geralmente não forneciam ajuda, exceto em situações de perigo contra os Aklats.
Alguns Orcs vivem sem tribo, considerados perigosos por não seguirem as tradições. Eles se esforçam para resolver conflitos na Arena de Sangue, mesmo fora do deserto, mantendo um código de honra entre eles.";

const AIGLA_ID := 0x9E7;
const ALURIEL_ID := 0x9E8;
const BADURAN_ID := 0x9E9;
const BJORSKA_ID := 0x9EA;
const GULTHRAK_ID := 0x9EB;
const HAROLOTH_ID := 0x9EC;
const POLKINEA_ID := 0x9ED;
const LESTE_ID := 0x9EE;

var CULTURA := struct{AIGLANA := "Aiglana", HAROLOTH := "Har'oloth", LESTE := "Povos do Leste", BJORSKA := "Björska", ALURIEL := "Alüriel", BADURAN := "Badûran", GULTHRAK := "Gulthrak", POLKINEA := "Polkinea"};
var RACA := struct{ANAO := "Anão", DROW := "Drow", ELFO := "Elfo", ORC := "Orc", HUMANO :="Humano", POLSKI := "Polski"};
var BACKGROUNDS := struct{DOMESTIC_WORK := "Mestre do Lar", METAL_WORK := "Ferreiro aprendiz", GATHERING := "Coletor", PICK_POCKETING := "Rato de rua", MECHANICAL_APITUDE := "Aventureiro", HANDLE_ANIMAL := "Domador de Feras", SURVIVAL := "Caçador", MEDICINE := "Curandeiro itinerante", WOOD_WORK := "Marceneiro"};
var CULTURAL_BACKGROUNDS := struct{ "Aiglana" := "Legionário", "Har'oloth" := "Véu de Idrith", "Polkinea" := "Pés Leves", "Alüriel" := "Templo da Mente", "Björska" := "Escaramuçador", "Gulthrak" := "Brutamontes", "Badûran" := "Filho da Montanha", "Povos do Leste" := "Andarilho"};

function getCultureByPictureId(culture_id)
    case (culture_id)
        AIGLA_ID:
            return CULTURA.AIGLANA;
        ALURIEL_ID:
            return CULTURA.ALURIEL;
        BADURAN_ID:
            return CULTURA.BADURAN;
        BJORSKA_ID:
            return CULTURA.BJORSKA;
        GULTHRAK_ID:
            return CULTURA.GULTHRAK;
        HAROLOTH_ID:
            return CULTURA.HAROLOTH;
        POLKINEA_ID:
            return CULTURA.POLKINEA;
        LESTE_ID:
            return CULTURA.LESTE;
    endcase
endfunction

function CultureGump(who, culture_pic)
    var next_btn := array{"9903", "9904"};
    var prev_btn := array{"9909", "9910"};

    var gump := GFCreateGump();
    GFGumpPic(gump, 17, 31, 0x9E6);

    GFHTMLArea(gump, 346, 56, 192, 40, "<BASEFONT Size=55 Color=#999999 >Escolha sua cultura", 0, 0); //shadow
    GFHTMLArea(gump, 345, 55, 192, 40, "<BASEFONT Size=55 Color=#ffffff >Escolha sua cultura", 0, 0);
    var x := 63;
    var y := 100;
    var i := 0;

    GFHTMLArea(gump, 100, 550, 650, 120, getCulturalDescriptionByPictureId(culture_pic), 1, 1);
    GFAddButton(gump, 543, 300, next_btn[1], next_btn[2], GF_CLOSE_BTN, 201);
    GFAddButton(gump, 273, 300, prev_btn[1], prev_btn[2], GF_CLOSE_BTN, 210);
    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);

    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function getCulturalDescriptionByPictureId(culture_id)
    case (culture_id)
        AIGLA_ID:
            return aiglaText;
        ALURIEL_ID:
            return alurielText;
        BADURAN_ID:
            return baduranText;
        BJORSKA_ID:
            return bjorskaText;
        GULTHRAK_ID:
            return gulthrakText;
        HAROLOTH_ID:
            return harolothText;
        POLKINEA_ID:
            return polkineaText;
        LESTE_ID:
            return lesteText;
    endcase
endfunction

function RaceGump(who, culture_pic)
    var races := getRaceByCulturalId(culture_pic);
    var gump := GFCreateGump();

    var x := 63;
    var y := 100;
    var i := 1;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    var raceText := "Escolha sua raça";
    if (races.size() == 1)
        raceText := "Raça selecionada";
    endif
    GFHTMLArea(gump, x+21, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > "+raceText, 0, 0); //shadow
    GFHTMLArea(gump, x+20, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > "+raceText, 0, 0);
    

    foreach race in races
        var color := "#000000";
        GFHTMLArea(gump, x, y, 192, 24, "<BASEFONT color=#{}>{}".format(color, race), 1, 0);
        if (races.size() > 1)
            GFRadioButton(gump, x+201, y, 0x9C4E, 0x9C4F, 0, 200+i);
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);
    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function getRaceByCulturalId(culture_pic)
    var races;
    case (culture_pic)
        HAROLOTH_ID:
            races := {RACA.DROW};
        ALURIEL_ID:
            races := {RACA.ELFO};
        POLKINEA_ID:
            races := {RACA.POLSKI};
        GULTHRAK_ID:
            races := {RACA.ORC};
        BADURAN_ID:
            races := {RACA.ANAO};
        BJORSKA_ID:
            races := {RACA.HUMANO};
        default:
            races := array{RACA.ANAO, RACA.DROW, RACA.ELFO, RACA.HUMANO, RACA.ORC, RACA.POLSKI};
    endcase
    return races;
endfunction

function ClassGump(who, culture_pic)
    var gump := GFCreateGump();

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+16, y+40, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seu caminho", 0, 0); //shadow
    GFHTMLArea(gump, x+15, y+39, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha seu caminho", 0, 0);

    var all_classes := array{ 
        "Caminho das Armas",
		"Caminho do Subterfúgio",
		"Caminho da Sabedoria"
    };
    foreach class in (all_classes)
        GFHTMLArea(gump, x, y+65, 192, 24, "<BASEFONT color=#000000>{}".format(class), 1, 0);
        GFRadioButton(gump, x+201, y+65, 0x9C4E, 0x9C4F, 0, 200+i);

        sleepms(2);
        y += 26;
        i++;
    endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);
    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function backgroundGump(who, culture_pic)
    var gump := GFCreateGump();

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+16, y+96, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seu passado", 0, 0); //shadow
    GFHTMLArea(gump, x+15, y+95, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha seu passado", 0, 0);

    var all_backgrounds := BACKGROUNDS;
    VAR cultural_bg := backgroundByCulture(who);
    var cfg := ReadConfigFile(":charactercreation:config/backgrounds");
    foreach bg in (all_backgrounds)
        GFHTMLArea(gump, x, y+116, 192, 24, "<BASEFONT color=#ffffff>{}".format(bg), 1, 0);
        GFToolTipText(gump, cfg[bg].Desc);
        GFRadioButton(gump, x+201, y+116, 0x9C4E, 0x9C4F, 0, 200+i);
        sleepms(2);
        y += 26;
        i++;
    endforeach
    GFHTMLArea(gump, x, y+116, 192, 24, "<BASEFONT color=#ffffff>{}".format(cultural_bg), 1, 0);
    GFToolTipText(gump, cfg[cultural_bg].Desc);

    GFRadioButton(gump, x+201, y+116, 0x9C4E, 0x9C4F, 0, 200+i);

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);


    return GFSendGump(who, gump);
endfunction

function backgroundByCulture(who)
    var chardata := GetObjProperty(who, "chardata");
    var culture := chardata.culture;

    return CULTURAL_BACKGROUNDS[culture];
endfunction

function traitGump(who, culture_pic, traits)
    var gump := GFCreateGump();

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+21, y+136, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha sua Característica", 0, 0); //shadow
    GFHTMLArea(gump, x+20, y+135, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha sua Característica", 0, 0);

	foreach trait in traits
        var trait_name := trait.nome;
        var trait_desc := trait.desc;
        var trait_adv := trait.Vantagens;
        
        GFHTMLArea(gump, x, y+151, 192, 24, "<BASEFONT color=#ffffff >{}".format(trait_name), 1, 0);
        GFTooltipText(gump, "{}<br><BASEFONT color=#ffffff>".format(trait_desc));
        GFTooltipText(gump, "{}<br><BASEFONT color=#ffffff>".format(trait_adv));
        GFRadioButton(gump, x+201, y+151, 0x9C4E, 0x9C4F, 0, 200+i);
        sleepms(2);
        y += 26;
        i++;
	endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);

    return GFSendGump(who, gump);
endfunction

function GetSkillValueDesc(skill)

	if (!skill || skill == error)
		return "";
	elseif (skill == 1)
		return "Terciária";
	elseif (skill == 2)
		return "Secundária";
	elseif (skill == 3)
		return "Primária";
	endif

endfunction

function listTraits(who, chardata)

	var cfg := ReadConfigFile(":charactercreation:config/traits");
	var keys := GetConfigStringKeys( cfg );

	var traits := array;
	var selectedtrait := 1;
	foreach key in keys
		var elem  := FindConfigElem(cfg, key);
		var canadd := 1;
		var racas := GetConfigStringArray( elem, "Raca" );
		var culturas := GetConfigStringArray( elem, "Cultura" );
		var classes := GetConfigStringArray( elem, "Classe" );

		if ((racas.size() >= 1) && !(chardata.race in racas))
			canadd := 0;
		endif
		if ((classes.size()>=1) && !(chardata.classe in classes))
			canadd := 0;
		endif
		if ((culturas.size() >= 1) && !(chardata.culture in culturas))
			canadd := 0;
		endif

		if (canadd)
			var trait  := struct;
			trait.+nome := GetconfigString(elem, "Nome");
			trait.+desc := GetconfigString(elem, "Desc");
			trait.+vantagens := GetConfigString( elem, "Vantagens" );
			trait.+desvantagens := GetConfigString( elem, "Desvantagens" );
			traits.append(trait);
		endif
	endforeach

    return traits;
endfunction

function showPreviousGumpInformation(byref gump, who, culture_pic := 0, x, y)
    GFGumpPic(gump, 17, 31, 0x9E6);

    var chardata := GetObjProperty(who, "chardata");
    chardata.+Primarias;
    var race := chardata.race;
    var color := "#FFD700";
    var class := chardata.classe;
    var bg := chardata.background;
    var trait := chardata.trait;
    var skills := chardata.Skills;
    if (race)
        GFHTMLArea(gump, x+86, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > Raça", 0, 0); //shadow
        GFHTMLArea(gump, x+85, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Raça", 0, 0);
        GFHTMLArea(gump, x+16, y, 192, 24, "<BASEFONT color=#{}>{}".format(color, race), 1, 0);
    endif

    if (culture_pic)
        GFHTMLArea(gump, 346, 66, 192, 40, "<BASEFONT Size=55 Color=#999999 > Cultura selecionada", 0, 0); //shadow
        GFHTMLArea(gump, 345, 65, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Cultura selecionada", 0, 0);
        GFGumpPic(gump, 298, 100, culture_pic);
    endif

    if (class)
        GFHTMLArea(gump, x+81, y+29, 192, 40, "<BASEFONT Size=55 Color=#999999 > Classe", 0, 0); //shadow
        GFHTMLArea(gump, x+80, y+30, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Classe", 0, 0);
        GFHTMLArea(gump, x+16, y+51, 192, 24, "<BASEFONT color=#{}>{}".format(color, class), 1, 0);
    endif

    if (bg)
        GFHTMLArea(gump, x+81, y+82, 192, 40, "<BASEFONT Size=55 Color=#999999 > Passado", 0, 0); //shadow
        GFHTMLArea(gump, x+80, y+81, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Passado", 0, 0);
        GFHTMLArea(gump, x+16, y+101, 192, 24, "<BASEFONT color=#{}>{}".format(color, bg), 1, 0);
    endif

    if (trait)
        GFHTMLArea(gump, x+61, y+132, 192, 40, "<BASEFONT Size=55 Color=#999999 > Característica", 0, 0); //shadow
        GFHTMLArea(gump, x+60, y+131, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Característica", 0, 0);
        GFHTMLArea(gump, x+16, y+151, 192, 24, "<BASEFONT color=#{}>{}".format(color, trait), 1, 0);
    endif

    if (skills)
        GFHTMLArea(gump, x+81, y+182, 192, 40, "<BASEFONT Size=55 Color=#999999 > Skills", 0, 0); //shadow
        GFHTMLArea(gump, x+80, y+181, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Skills", 0, 0);
        //foreach skill in (skills.keys())
        //    if (skills[skill] > 0)
        //        GFHTMLArea(gump, x+16, y+201, 192, 24, "<BASEFONT color=#{}>{} | {}".format(color, skill, GetSkillValueDesc(skills[skill])), 1, 0); //shadow
        //        y+=30;
        //    endif
        //endforeach
    endif
endfunction

function skillGump(who, culture_pic, byref chardata)
    var gump := GFCreateGump();
    //var chardata := GetObjProperty(who, "chardata");
    var minus_btn := {0x9F7, 0x9F6};
    var plus_btn := {0x9F9, 0x9F8};
    var pri_allowed := howManyPrimarias(chardata);

    var x := 63;
    var y := 100;
    var i := 1;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    x := 555;
    y := 100;
    GFHTMLArea(gump, x+1, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha suas skills", 0, 0); //shadow
    GFHTMLArea(gump, x, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha suas skills", 0, 0);
    var cfg;
    var elem;

    cfg := ReadConfigFile(":charactercreation:config/classes");
    elem := FindConfigElem(cfg, cstr(chardata.classe));

    var primarias    := GetConfigStringArray(elem, "P");
    var secundarias  := GetConfigStringArray(elem, "S");
    var terciarias   := GetConfigStringArray(elem, "T");
    var quaternarias := GetConfigStringArray(elem, "Q");
    var value := 1;

    x+=10;
    foreach skill in primarias
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#0000CC >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 100+GetSkillIdFromName(skill));
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 120+GetSkillIdFromName(skill));
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    y+=10;
    value := 2;
    foreach skill in secundarias
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#007A23 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 200+GetSkillIdFromName(skill));
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 220+GetSkillIdFromName(skill));
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    y+=10;
    value := 3;
    foreach skill in terciarias
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#FFE700 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 300+GetSkillIdFromName(skill));
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 320+GetSkillIdFromName(skill));
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    y+=10;
    value := 4;
    foreach skill in quaternarias
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#CC0000 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 400+GetSkillIdFromName(skill));
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 420+GetSkillIdFromName(skill));
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    var count := 0;
    var skills := chardata.Skills;
    y := 300;
    x := 73;
    var color := "FFFFFF";
    chardata.Primarias := 0;
    foreach skill in (skills.keys())
        if (skills[skill] == 3)
            chardata.Primarias++;
            color := "0000CC";
        elseif (skills[skill] == 2)
            color := "007A23";
        elseif (skills[skill] == 1)
            color := "FFE700";
        endif
        if (skills[skill] > 0)
            GFHTMLArea(gump, x, y, 192, 24, "<BASEFONT color=#{}>{} | {}".format(color, skill, GetSkillValueDesc(skills[skill])), 1, 0); //shadow
            y+=30;
        endif
    endforeach
    
    SetObjProperty(who, "chardata", chardata);
    GFHTMLArea(gump, 345, 515, 192, 40, "<BASEFONT Size=55 Color=#999999 > Pontos restantes", 0, 0);
    GFHTMLArea(gump, 346, 516, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Pontos restantes", 0, 0); //shadow
    GFHTMLArea(gump, 400, 536, 135, 24, "<BASEFONT color=#FFE700 >{}".format(chardata.points), 0, 0);
    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 500); // Botão de fechar

    return GFSendGump(who, gump);
endfunction

function howManyPrimarias(chardata)
    if (chardata.trait == "Sabe-Tudo")
        return 1;
    endif

    return 2;
endfunction
